/*
 * Backpack - Skyscanner's Design System
 *
 * Copyright 2016-2019 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

module.exports = {
  HOME: '/',
  USING_BACKPACK: '/using',
  TOKENS: '/tokens',
  GUIDELINES: '/guidelines',
  GETTING_STARTED: '/using/getting-started',
  BACKPACK_REACT_SCRIPTS: '/using/backpack-react-scripts',
  BASE_STYLESHEET: '/using/base-stylesheet',
  PRINCIPLES: '/using/principles',
  STATUS: '/using/status',
  ACCESSIBILITY: '/guidelines/accessibility',
  ACCESSIBILITY_OVERVIEW: '/guidelines/accessibility/overview',
  ACCESSIBILITY_DESIGN: '/guidelines/accessibility/design',
  COLORS: '/guidelines/colors',
  COPYWRITING: '/guidelines/copywriting',
  GRAPHIC_DEVICES: '/guidelines/graphic-devices',
  ICONOGRAPHY: '/guidelines/iconography',
  ILLUSTRATION: '/guidelines/illustration',
  IN_USE: '/guidelines/in-use',
  LOGO: '/guidelines/logo',
  PHOTOGRAPHY: '/guidelines/photography',
  TONE_OF_VOICE: '/guidelines/tone-of-voice',
  SHADOWS_GUIDELINES: '/guidelines/shadows',
  STRATEGY: '/guidelines/strategy',
  TYPOGRAPHY: '/guidelines/typography',
  TYPESETTING: '/tokens/typesetting',
  RADII: '/tokens/radii',
  SHADOWS: '/tokens/shadows',
  BORDERS: '/tokens/borders',
  SPACINGS: '/tokens/spacings',
  ANIMATION: '/tokens/animation',
  Z_INDEXES: '/tokens/z-indexes',
  COMPONENTS: '/components',
  TEXT: '/components/text',
  TEXT_INPUT: '/components/text-input',
  TEXT_VIEW: '/components/text-view',
  TAPPABLE_LINK_LABEL: '/components/tappable-link-label',
  LINK: '/components/link',
  LIST: '/components/list',
  DESCRIPTION_LIST: '/components/description-list',
  TABLE: '/components/table',
  BLOCKQUOTE: '/components/blockquote',
  CODE: '/components/code',
  BUTTON: '/components/button',
  BUTTON_LINK: '/components/button-link',
  BOTTOM_SHEET: '/components/bottom-sheet',
  ICON: '/components/icon',
  SPINNER: '/components/spinner',
  FLOATING_ACTION_BUTTON: '/components/floating-action-button',
  RATING: '/components/rating',
  TOAST: '/components/toast',
  TEXT_SPANS: '/components/text-spans',
  STAR_RATING_INTERACTIVE: '/components/star-rating-interactive',
  CHECKBOX: '/components/checkbox',
  SNACKBAR: '/components/snackbar',
  FORM: '/components/form',
  FORM_LABEL: '/components/form-label',
  FORM_VALIDATION: '/components/form-validation',
  CARD: '/components/card',
  CHIP: '/components/chip',
  BADGE: '/components/badge',
  PANEL: '/components/panel',
  IMAGE: '/components/image',
  BANNER_ALERT: '/components/banner-alert',
  ALERT: '/components/alert',
  MOBILE_SCROLL_CONTAINER: '/components/mobile-scroll-container',
  MODAL: '/components/modal',
  AUTOSUGGEST: '/components/autosuggest',
  POPOVER: '/components/popover',
  CALENDAR: '/components/calendar',
  DATEPICKER: '/components/datepicker',
  TOOLTIP: '/components/tooltip',
  ACCORDION: '/components/accordion',
  NUDGER: '/components/nudger',
  PROGRESS: '/components/progress',
  RADIO_BUTTON: '/components/radio-button',
  TICKET: '/components/ticket',
  HORIZONTAL_NAV: '/components/horizontal-nav',
  FIELDSET: '/components/fieldset',
  BARCHART: '/components/barchart',
  PAGINATION: '/components/pagination',
  STAR_RATING: '/components/star-rating',
  BREAKPOINT: '/components/breakpoint',
  HORIZONTAL_GRID: '/components/horizontal-grid',
  SCROLLABLE_CALENDAR: '/components/scrollable-calendar',
  SLIDER: '/components/slider',
  DRAWER: '/components/drawer',
  DIALOG: '/components/dialog',
  FLAT_LIST: '/components/flat-list',
  NAVIGATION_BAR: '/components/navigation-bar',
  NAVIGATION_STACK: '/components/navigation-stack',
  PHONE_INPUT: '/components/phone-input',
  PICKER: '/components/picker',
  SECTION_LIST: '/components/section-list',
  SWITCH: '/components/switch',
  SELECT: '/components/select',
  TOUCHABLE_OVERLAY: '/components/touchable-overlay',
  TOUCHABLE_NATIVE_FEEDBACK: '/components/touchable-native-feedback',
  MAP: '/components/map',
  CAROUSEL: '/components/carousel',
  INFINITE_SCROLL: '/components/infinite-scroll',
  BREADCRUMB: '/components/breadcrumb',
  FLARE: '/components/flare',
  BOTTOM_NAV: '/components/bottom-nav',
  ALIGNMENT: '/components/alignment',
  THEMING: '/components/theming',
  UTILITIES: '/components/utilities',
  GRID_COLUMN_DEMO: '/grid-column-demo',
  GRID_OFFSET_DEMO: '/grid-offset-demo',
  BAG_CHECK: '/bag-check-bookmarklet',
};
