name: Backpack Docs CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo that triggered this action'
        required: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: nvm install
        run: nvm install

      - name: nvm use
        run: nvm use

      - name: Check out submodules
        run: |
          git submodule update --init --recursive
          npm run submodules:pull

      - name: Clear the cache
        run: npm cache clean --force

      - name: Install deps
        run: |
          nvm use
          npm ci

      - name: Danger
        run: npm run danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

      - name: Test
        run: npm test

      - name: Build website
        run: |
          nvm use
          npm run docs:dist

      - name: Check site was built correctly
        run: test -e dist/index.html

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: dist/
          keep_files: true
          external_repository: backpack/backpack.github.io
          publish_branch: master
